packages:
  - e2e-tests
  - e2e-tests/templates/vue
  - tests/visual
  - tests/behavior
  - apps/*
  - packages/**/*
  - shared/*
  - examples/*

catalog:
  '@commitlint/cli': ^19.8.1
  '@commitlint/config-conventional': ^19.8.1
  '@eslint/js': ^9.31.0
  '@floating-ui/dom': ^1.7.0
  '@fontsource/inter': ^5.2.8
  '@hocuspocus/provider': ^2.13.6
  '@hocuspocus/server': ^2.13.6
  '@linear/sdk': ^53.0.0
  '@playwright/test': ^1.57.0
  '@semantic-release/changelog': ^6.0.3
  '@semantic-release/git': ^10.0.1
  '@testing-library/jest-dom': ^6.9.1
  '@testing-library/react': ^16.3.0
  '@testing-library/user-event': ^14.6.1
  '@types/bun': ^1.3.8
  '@types/node': 22.19.2
  '@types/react': ^19.2.6
  '@types/react-dom': ^19.2.3
  '@typescript-eslint/eslint-plugin': ^8.49.0
  '@typescript-eslint/parser': ^8.49.0
  '@vitejs/plugin-react': ^5.1.1
  '@vitejs/plugin-vue': 6.0.2
  '@vitest/coverage-v8': ^3.2.4
  '@vue/test-utils': ^2.4.6
  buffer-crc32: ^1.0.0
  canvas: ^3.2.0
  color2k: ^2.0.3
  concurrently: ^9.1.2
  dotenv: ^16.4.7
  eslint: ^9.39.1
  eslint-config-prettier: ^9.1.0
  eslint-import-resolver-typescript: ^4.4.4
  eslint-plugin-import-x: ^4.16.1
  eslint-plugin-jsdoc: ^54.1.0
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^7.0.1
  eventemitter3: ^5.0.1
  fast-glob: ^3.3.3
  happy-dom: ^20.3.4
  he: ^1.2.0
  jimp: ^1.6.0
  jsdom: ^27.3.0
  jszip: 3.10.1
  konva: ^10.2.0
  lefthook: ^1.11.13
  lib0: ^0.2.114
  marked: ^16.2.0
  naive-ui: ^2.43.1
  nodemon: ^3.1.10
  patch-package: ^8.0.1
  pdfjs-dist: ^5.4.296
  pinia: ^2.1.7
  pixelmatch: ^7.1.0
  playwright: ^1.56.0
  postcss-nested: ^6.0.1
  postcss-nested-import: ^1.3.0
  postcss-prefixwrap: ^1.56.2
  prettier: 3.3.3
  prosemirror-commands: ^1.5.2
  prosemirror-dropcursor: ^1.8.1
  prosemirror-gapcursor: ^1.3.2
  prosemirror-history: ^1.4.0
  prosemirror-inputrules: ^1.4.0
  prosemirror-keymap: ^1.2.2
  prosemirror-model: ^1.25.2
  prosemirror-schema-basic: ^1.2.2
  prosemirror-schema-list: ^1.3.0
  prosemirror-state: ^1.4.3
  prosemirror-tables: ^1.4.0
  prosemirror-test-builder: ^1.1.1
  prosemirror-transform: ^1.9.0
  prosemirror-view: ^1.33.8
  react: 19.2.4
  react-dom: 19.2.4
  rehype-parse: ^9.0.1
  rehype-remark: ^10.0.1
  remark-gfm: ^4.0.1
  remark-stringify: ^11.0.0
  rollup-plugin-copy: ^3.5.0
  rollup-plugin-visualizer: ^5.12.0
  semantic-release: ^24.2.7
  semantic-release-commit-filter: ^1.0.2
  semantic-release-linear-app: ^0.7.1
  tippy.js: ^6.3.7
  tsup: ^8.5.1
  tsx: ^4.20.6
  typescript: ^5.9.2
  typescript-eslint: ^8.49.0
  unified: 11.0.5
  uuid: ^9.0.1
  verdaccio: ^6.1.6
  vite: ^7.2.7
  vite-plugin-dts: ~4.5.4
  vite-plugin-node-polyfills: ^0.25.0
  vitest: ^3.2.4
  vue: 3.5.25
  xml-js: 1.6.11
  y-prosemirror: ^1.3.7
  y-protocols: ^1.0.6
  y-websocket: ^3.0.0
  yjs: 13.6.19

onlyBuiltDependencies:
  - '@vscode/vsce-sign'
  - canvas
  - esbuild
  - keytar
  - lefthook
  - puppeteer
  - sharp
  - unrs-resolver
  - vue-demi

patchedDependencies:
  # readable-stream requires 'string_decoder/' with trailing slash; Rolldown treats it as a directory path
  readable-stream@3.6.2: patches/readable-stream@3.6.2.patch
