import { describe, expect, it } from 'vitest';

import { textToImageDataUrl } from '../utils/signature';

describe('textToImageDataUrl', () => {
  it('returns a data URL for a typed signature', () => {
    const result = textToImageDataUrl('Jane Doe');
    // the mock is generated by the test/setup.ts file
    expect(result).toBe('data:image/png;base64,mock');
  });
});
